DataDirectory: "./data"
Debug: False
GameStep: 4
# Visualize processed spatial information
# This shows exactly what will be passed through the conv layers
VisualizeSpatialFeatures: False
SquadAgent:
  AgentClass: "PPOAgent"
  CheckPointName: "checkpoint.pt"
  InferenceMode: False
  NumRolloutSteps: 64
  # Offline agent stores states, actions, rewards etc. here
  StateDirectory: "states"
  # setting specific to ppo agent (most of these used in `ppo_trainer.py`)
  PPO:
    BatchSize: 64
    ClipCoefficient: 0.01
    EntropyCoefficient: 0.01
    GaeLambda: 0.95
    Gamma: 0.99
    MaxGradNorm: 0.5
    NumRolloutSteps: 64
    UpdatePolicyEpochs: 4
    VFCoefficient: 0.5
