DataDirectory: "./data"
Debug: True
GameStep: 4
VisualizeSpatialFeatures: False
SquadAgent:
  AgentClass: "OfflineAgent"
  CheckPointName: "checkpoint.pt"
  # Keep on True for OfflineAgent
  InferenceMode: True
  # Offline agent stores states, actions, rewards etc. here
  StateDirectory: "/states"
