from enum import Enum, auto
from typing import Set, Dict

from sc2.ids.unit_typeid import UnitTypeId


class AgentClass(str, Enum):
    OFFLINE_AGENT = "OfflineAgent"
    RANDOM_AGENT = "RandomAgent"


class ConfigSettings(str, Enum):
    AGENT_CLASS = "AgentClass"
    DATA_DIRECTORY = "DataDirectory"
    DEBUG = "Debug"
    CHECKPOINT_NAME = "CheckPointName"
    GAME_STEP = "GameStep"
    INFERENCE_MODE = "InferenceMode"
    STATE_DIRECTORY = "StateDirectory"
    SQUAD_AGENT = "SquadAgent"
    VISUALIZE_SPATIAL_FEATURES = "VisualizeSpatialFeatures"


class SquadActionType(Enum):
    ATTACK_MOVE = auto()
    ATTACK_STUTTER_BACK = auto()
    ATTACK_STUTTER_FORWARD = auto()
    DESTROY_CLOSEST_ROCKS = auto()
    MOVE_TO_MAIN_OFFENSIVE_THREAT = auto()
    MOVE_TO_SAFE_SPOT = auto()
    HOLD_POSITION = auto()
    RETREAT_TO_RALLY_POINT = auto()
    STIM = auto()


SQUAD_ACTIONS: Dict[int, SquadActionType] = {
    0: SquadActionType.ATTACK_STUTTER_BACK,
    1: SquadActionType.ATTACK_STUTTER_FORWARD,
    2: SquadActionType.MOVE_TO_MAIN_OFFENSIVE_THREAT,
    3: SquadActionType.RETREAT_TO_RALLY_POINT,
    4: SquadActionType.HOLD_POSITION,
    5: SquadActionType.STIM,
}


class UnitRoleTypes(Enum):
    ATTACKING = auto()
    BUILDING = auto()
    GATHERING = auto()
    WORKER_DEFENDER = auto()


WORKERS_DEFEND_AGAINST: Set[UnitTypeId] = {
    UnitTypeId.DRONE,
    UnitTypeId.PROBE,
    UnitTypeId.SCV,
    UnitTypeId.ZERGLING,
}

ALL_STRUCTURES: Set[UnitTypeId] = {
    UnitTypeId.ARMORY,
    UnitTypeId.ASSIMILATOR,
    UnitTypeId.ASSIMILATORRICH,
    UnitTypeId.AUTOTURRET,
    UnitTypeId.BANELINGNEST,
    UnitTypeId.BARRACKS,
    UnitTypeId.BARRACKSFLYING,
    UnitTypeId.BARRACKSREACTOR,
    UnitTypeId.BARRACKSTECHLAB,
    UnitTypeId.BUNKER,
    UnitTypeId.BYPASSARMORDRONE,
    UnitTypeId.COMMANDCENTER,
    UnitTypeId.COMMANDCENTERFLYING,
    UnitTypeId.CREEPTUMOR,
    UnitTypeId.CREEPTUMORBURROWED,
    UnitTypeId.CREEPTUMORQUEEN,
    UnitTypeId.CYBERNETICSCORE,
    UnitTypeId.DARKSHRINE,
    UnitTypeId.ELSECARO_COLONIST_HUT,
    UnitTypeId.ENGINEERINGBAY,
    UnitTypeId.EVOLUTIONCHAMBER,
    UnitTypeId.EXTRACTOR,
    UnitTypeId.EXTRACTORRICH,
    UnitTypeId.FACTORY,
    UnitTypeId.FACTORYFLYING,
    UnitTypeId.FACTORYREACTOR,
    UnitTypeId.FACTORYTECHLAB,
    UnitTypeId.FLEETBEACON,
    UnitTypeId.FORGE,
    UnitTypeId.FUSIONCORE,
    UnitTypeId.GATEWAY,
    UnitTypeId.GHOSTACADEMY,
    UnitTypeId.GREATERSPIRE,
    UnitTypeId.HATCHERY,
    UnitTypeId.HIVE,
    UnitTypeId.HYDRALISKDEN,
    UnitTypeId.INFESTATIONPIT,
    UnitTypeId.LAIR,
    UnitTypeId.LURKERDENMP,
    UnitTypeId.MISSILETURRET,
    UnitTypeId.NEXUS,
    UnitTypeId.NYDUSCANAL,
    UnitTypeId.NYDUSCANALATTACKER,
    UnitTypeId.NYDUSCANALCREEPER,
    UnitTypeId.NYDUSNETWORK,
    UnitTypeId.ORACLESTASISTRAP,
    UnitTypeId.ORBITALCOMMAND,
    UnitTypeId.ORBITALCOMMANDFLYING,
    UnitTypeId.PHOTONCANNON,
    UnitTypeId.PLANETARYFORTRESS,
    UnitTypeId.POINTDEFENSEDRONE,
    UnitTypeId.PYLON,
    UnitTypeId.PYLONOVERCHARGED,
    UnitTypeId.RAVENREPAIRDRONE,
    UnitTypeId.REACTOR,
    UnitTypeId.REFINERY,
    UnitTypeId.REFINERYRICH,
    UnitTypeId.RESOURCEBLOCKER,
    UnitTypeId.ROACHWARREN,
    UnitTypeId.ROBOTICSBAY,
    UnitTypeId.ROBOTICSFACILITY,
    UnitTypeId.SENSORTOWER,
    UnitTypeId.SHIELDBATTERY,
    UnitTypeId.SPAWNINGPOOL,
    UnitTypeId.SPINECRAWLER,
    UnitTypeId.SPINECRAWLERUPROOTED,
    UnitTypeId.SPIRE,
    UnitTypeId.SPORECRAWLER,
    UnitTypeId.SPORECRAWLERUPROOTED,
    UnitTypeId.STARGATE,
    UnitTypeId.STARPORT,
    UnitTypeId.STARPORTFLYING,
    UnitTypeId.STARPORTREACTOR,
    UnitTypeId.STARPORTTECHLAB,
    UnitTypeId.SUPPLYDEPOT,
    UnitTypeId.SUPPLYDEPOTLOWERED,
    UnitTypeId.TECHLAB,
    UnitTypeId.TEMPLARARCHIVE,
    UnitTypeId.TWILIGHTCOUNCIL,
    UnitTypeId.ULTRALISKCAVERN,
    UnitTypeId.WARPGATE,
}

INFLUENCE_COSTS: Dict[UnitTypeId, Dict] = {
    UnitTypeId.ADEPT: {"AirCost": 0, "GroundCost": 9, "AirRange": 0, "GroundRange": 5},
    UnitTypeId.ADEPTPHASESHIFT: {
        "AirCost": 0,
        "GroundCost": 9,
        "AirRange": 0,
        "GroundRange": 5,
    },
    UnitTypeId.AUTOTURRET: {
        "AirCost": 31,
        "GroundCost": 31,
        "AirRange": 7,
        "GroundRange": 7,
    },
    UnitTypeId.ARCHON: {
        "AirCost": 40,
        "GroundCost": 40,
        "AirRange": 3,
        "GroundRange": 3,
    },
    UnitTypeId.BANELING: {
        "AirCost": 0,
        "GroundCost": 20,
        "AirRange": 0,
        "GroundRange": 3,
    },
    UnitTypeId.BANSHEE: {
        "AirCost": 0,
        "GroundCost": 12,
        "AirRange": 0,
        "GroundRange": 6,
    },
    UnitTypeId.BATTLECRUISER: {
        "AirCost": 31,
        "GroundCost": 50,
        "AirRange": 6,
        "GroundRange": 6,
    },
    UnitTypeId.BUNKER: {
        "AirCost": 22,
        "GroundCost": 22,
        "AirRange": 6,
        "GroundRange": 6,
    },
    UnitTypeId.CARRIER: {
        "AirCost": 20,
        "GroundCost": 20,
        "AirRange": 11,
        "GroundRange": 11,
    },
    UnitTypeId.CORRUPTOR: {
        "AirCost": 10,
        "GroundCost": 0,
        "AirRange": 6,
        "GroundRange": 0,
    },
    UnitTypeId.CYCLONE: {
        "AirCost": 27,
        "GroundCost": 27,
        "AirRange": 7,
        "GroundRange": 7,
    },
    UnitTypeId.GHOST: {
        "AirCost": 10,
        "GroundCost": 10,
        "AirRange": 6,
        "GroundRange": 6,
    },
    UnitTypeId.HELLION: {
        "AirCost": 0,
        "GroundCost": 8,
        "AirRange": 0,
        "GroundRange": 8,
    },
    UnitTypeId.HYDRALISK: {
        "AirCost": 20,
        "GroundCost": 20,
        "AirRange": 6,
        "GroundRange": 6,
    },
    UnitTypeId.INFESTOR: {
        "AirCost": 30,
        "GroundCost": 30,
        "AirRange": 10,
        "GroundRange": 10,
    },
    UnitTypeId.LIBERATOR: {
        "AirCost": 10,
        "GroundCost": 0,
        "AirRange": 5,
        "GroundRange": 0,
    },
    UnitTypeId.MARINE: {
        "AirCost": 10,
        "GroundCost": 10,
        "AirRange": 5,
        "GroundRange": 5,
    },
    UnitTypeId.MOTHERSHIP: {
        "AirCost": 23,
        "GroundCost": 23,
        "AirRange": 7,
        "GroundRange": 7,
    },
    UnitTypeId.MUTALISK: {
        "AirCost": 8,
        "GroundCost": 8,
        "AirRange": 3,
        "GroundRange": 3,
    },
    UnitTypeId.ORACLE: {
        "AirCost": 0,
        "GroundCost": 24,
        "AirRange": 0,
        "GroundRange": 4,
    },
    UnitTypeId.PHOENIX: {
        "AirCost": 15,
        "GroundCost": 0,
        "AirRange": 7,
        "GroundRange": 0,
    },
    UnitTypeId.PHOTONCANNON: {
        "AirCost": 22,
        "GroundCost": 22,
        "AirRange": 7,
        "GroundRange": 7,
    },
    UnitTypeId.QUEEN: {
        "AirCost": 12.6,
        "GroundCost": 11.2,
        "AirRange": 7,
        "GroundRange": 5,
    },
    UnitTypeId.SENTRY: {
        "AirCost": 8.4,
        "GroundCost": 8.4,
        "AirRange": 5,
        "GroundRange": 5,
    },
    UnitTypeId.SPINECRAWLER: {
        "AirCost": 0,
        "GroundCost": 15,
        "AirRange": 0,
        "GroundRange": 7,
    },
    UnitTypeId.STALKER: {
        "AirCost": 10,
        "GroundCost": 10,
        "AirRange": 6,
        "GroundRange": 6,
    },
    UnitTypeId.TEMPEST: {
        "AirCost": 17,
        "GroundCost": 17,
        "AirRange": 14,
        "GroundRange": 10,
    },
    UnitTypeId.THOR: {
        "AirCost": 28,
        "GroundCost": 28,
        "AirRange": 11,
        "GroundRange": 7,
    },
    UnitTypeId.VIKINGASSAULT: {
        "AirCost": 0,
        "GroundCost": 17,
        "AirRange": 0,
        "GroundRange": 6,
    },
    UnitTypeId.VIKINGFIGHTER: {
        "AirCost": 14,
        "GroundCost": 0,
        "AirRange": 9,
        "GroundRange": 0,
    },
    UnitTypeId.VOIDRAY: {
        "AirCost": 20,
        "GroundCost": 20,
        "AirRange": 6,
        "GroundRange": 6,
    },
    UnitTypeId.WIDOWMINEBURROWED: {
        "AirCost": 150,
        "GroundCost": 150,
        "AirRange": 5.5,
        "GroundRange": 5.5,
    },
}

UNIT_DATA: Dict[UnitTypeId, Dict] = {
    UnitTypeId.SCV: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 0.5},
    UnitTypeId.MULE: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitTypeId.MARINE: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 1},
    UnitTypeId.MARAUDER: {"minerals": 100, "gas": 25, "supply": 2, "army_value": 2},
    UnitTypeId.REAPER: {"minerals": 50, "gas": 50, "supply": 1, "army_value": 1},
    UnitTypeId.GHOST: {"minerals": 150, "gas": 125, "supply": 2, "army_value": 2},
    UnitTypeId.HELLION: {"minerals": 100, "gas": 0, "supply": 2, "army_value": 2},
    UnitTypeId.HELLIONTANK: {"minerals": 100, "gas": 0, "supply": 2, "army_value": 2},
    UnitTypeId.WIDOWMINE: {"minerals": 75, "gas": 25, "supply": 2, "army_value": 2},
    UnitTypeId.WIDOWMINEBURROWED: {
        "minerals": 75,
        "gas": 25,
        "supply": 2,
        "army_value": 2,
    },
    UnitTypeId.SIEGETANK: {"minerals": 150, "gas": 125, "supply": 3, "army_value": 3},
    UnitTypeId.SIEGETANKSIEGED: {
        "minerals": 150,
        "gas": 125,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.CYCLONE: {"minerals": 150, "gas": 100, "supply": 3, "army_value": 3},
    UnitTypeId.THOR: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitTypeId.THORAP: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitTypeId.VIKINGASSAULT: {
        "minerals": 150,
        "gas": 75,
        "supply": 2,
        "army_value": 2,
    },
    UnitTypeId.VIKINGFIGHTER: {
        "minerals": 150,
        "gas": 75,
        "supply": 2,
        "army_value": 2,
    },
    UnitTypeId.MEDIVAC: {"minerals": 100, "gas": 100, "supply": 2, "army_value": 2},
    UnitTypeId.LIBERATOR: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitTypeId.LIBERATORAG: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitTypeId.BANSHEE: {"minerals": 150, "gas": 100, "supply": 3, "army_value": 3},
    UnitTypeId.RAVEN: {"minerals": 100, "gas": 200, "supply": 2, "army_value": 2},
    UnitTypeId.BATTLECRUISER: {
        "minerals": 400,
        "gas": 300,
        "supply": 6,
        "army_value": 7,
    },
    UnitTypeId.POINTDEFENSEDRONE: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 1,
    },
    UnitTypeId.PROBE: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 0.5},
    UnitTypeId.ZEALOT: {"minerals": 100, "gas": 0, "supply": 2, "army_value": 2},
    UnitTypeId.SENTRY: {"minerals": 50, "gas": 100, "supply": 2, "army_value": 2},
    UnitTypeId.STALKER: {"minerals": 125, "gas": 50, "supply": 2, "army_value": 2},
    UnitTypeId.ADEPT: {"minerals": 100, "gas": 25, "supply": 2, "army_value": 2},
    UnitTypeId.ADEPTPHASESHIFT: {
        "minerals": 100,
        "gas": 25,
        "supply": 2,
        "army_value": 2,
    },
    UnitTypeId.HIGHTEMPLAR: {"minerals": 50, "gas": 150, "supply": 2, "army_value": 2},
    UnitTypeId.DARKTEMPLAR: {"minerals": 125, "gas": 125, "supply": 2, "army_value": 2},
    UnitTypeId.ARCHON: {"minerals": 175, "gas": 275, "supply": 4, "army_value": 5},
    UnitTypeId.OBSERVER: {"minerals": 25, "gas": 75, "supply": 1, "army_value": 0.25},
    UnitTypeId.OBSERVERSIEGEMODE: {
        "minerals": 25,
        "gas": 75,
        "supply": 1,
        "army_value": 0.25,
    },
    UnitTypeId.WARPPRISM: {"minerals": 200, "gas": 0, "supply": 2, "army_value": 2},
    UnitTypeId.WARPPRISMPHASING: {
        "minerals": 200,
        "gas": 0,
        "supply": 2,
        "army_value": 2,
    },
    UnitTypeId.IMMORTAL: {"minerals": 275, "gas": 100, "supply": 4, "army_value": 4},
    UnitTypeId.COLOSSUS: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitTypeId.DISRUPTOR: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitTypeId.DISRUPTORPHASED: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 3},
    UnitTypeId.PHOENIX: {"minerals": 150, "gas": 100, "supply": 2, "army_value": 2},
    UnitTypeId.VOIDRAY: {"minerals": 250, "gas": 150, "supply": 4, "army_value": 4},
    UnitTypeId.ORACLE: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitTypeId.TEMPEST: {"minerals": 250, "gas": 175, "supply": 5, "army_value": 5},
    UnitTypeId.CARRIER: {"minerals": 350, "gas": 250, "supply": 6, "army_value": 8},
    UnitTypeId.INTERCEPTOR: {"minerals": 15, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitTypeId.MOTHERSHIP: {"minerals": 300, "gas": 300, "supply": 8, "army_value": 8},
    UnitTypeId.LARVA: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.EGG: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.DRONE: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 0.5},
    UnitTypeId.DRONEBURROWED: {
        "minerals": 50,
        "gas": 0,
        "supply": 1,
        "army_value": 0.5,
    },
    UnitTypeId.QUEEN: {"minerals": 150, "gas": 0, "supply": 2, "army_value": 2},
    UnitTypeId.QUEENBURROWED: {"minerals": 150, "gas": 0, "supply": 2, "army_value": 2},
    UnitTypeId.ZERGLING: {"minerals": 25, "gas": 0, "supply": 0.5, "army_value": 0.5},
    UnitTypeId.ZERGLINGBURROWED: {
        "minerals": 25,
        "gas": 0,
        "supply": 0.5,
        "army_value": 0.5,
    },
    UnitTypeId.BANELINGCOCOON: {
        "minerals": 25,
        "gas": 25,
        "supply": 0.5,
        "army_value": 1,
    },
    UnitTypeId.BANELING: {"minerals": 25, "gas": 25, "supply": 0.5, "army_value": 1},
    UnitTypeId.BANELINGBURROWED: {
        "minerals": 25,
        "gas": 25,
        "supply": 0.5,
        "army_value": 1,
    },
    UnitTypeId.ROACH: {"minerals": 75, "gas": 25, "supply": 2, "army_value": 2},
    UnitTypeId.ROACHBURROWED: {"minerals": 75, "gas": 25, "supply": 2, "army_value": 2},
    UnitTypeId.RAVAGER: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.RAVAGERBURROWED: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.RAVAGERCOCOON: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.HYDRALISK: {"minerals": 100, "gas": 50, "supply": 2, "army_value": 2},
    UnitTypeId.HYDRALISKBURROWED: {
        "minerals": 100,
        "gas": 50,
        "supply": 2,
        "army_value": 2,
    },
    UnitTypeId.LURKERMP: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.LURKERMPBURROWED: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.LURKERMPEGG: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.INFESTOR: {"minerals": 100, "gas": 150, "supply": 2, "army_value": 2},
    UnitTypeId.INFESTEDTERRANSEGG: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.INFESTEDTERRAN: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.INFESTORTERRAN: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.INFESTORBURROWED: {
        "minerals": 100,
        "gas": 150,
        "supply": 2,
        "army_value": 2,
    },
    UnitTypeId.SWARMHOSTMP: {"minerals": 100, "gas": 75, "supply": 3, "army_value": 3},
    UnitTypeId.SWARMHOSTBURROWEDMP: {
        "minerals": 100,
        "gas": 75,
        "supply": 3,
        "army_value": 3,
    },
    UnitTypeId.LOCUSTMP: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.5},
    UnitTypeId.LOCUSTMPFLYING: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.5,
    },
    UnitTypeId.ULTRALISK: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitTypeId.ULTRALISKBURROWED: {
        "minerals": 300,
        "gas": 200,
        "supply": 6,
        "army_value": 6,
    },
    UnitTypeId.OVERLORD: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 0.1},
    UnitTypeId.OVERLORDCOCOON: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.1,
    },
    UnitTypeId.OVERLORDTRANSPORT: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.5,
    },
    UnitTypeId.TRANSPORTOVERLORDCOCOON: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.1,
    },
    UnitTypeId.OVERSEER: {"minerals": 150, "gas": 50, "supply": 0, "army_value": 0.5},
    UnitTypeId.OVERSEERSIEGEMODE: {
        "minerals": 150,
        "gas": 50,
        "supply": 0,
        "army_value": 0.5,
    },
    UnitTypeId.CHANGELING: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitTypeId.CHANGELINGMARINE: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitTypeId.CHANGELINGMARINESHIELD: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitTypeId.CHANGELINGZEALOT: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitTypeId.CHANGELINGZERGLING: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitTypeId.CHANGELINGZERGLINGWINGS: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitTypeId.MUTALISK: {"minerals": 100, "gas": 100, "supply": 2, "army_value": 2},
    UnitTypeId.CORRUPTOR: {"minerals": 150, "gas": 100, "supply": 2, "army_value": 2},
    UnitTypeId.VIPER: {"minerals": 100, "gas": 200, "supply": 3, "army_value": 3},
    UnitTypeId.BROODLORD: {
        "minerals": 150 + 150,
        "gas": 150 + 100,
        "supply": 4,
        "army_value": 6,
    },
    UnitTypeId.BROODLORDCOCOON: {
        "minerals": 150 + 150,
        "gas": 150 + 100,
        "supply": 4,
        "army_value": 6,
    },
    UnitTypeId.BROODLING: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitTypeId.COMMANDCENTER: {"minerals": 400, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.COMMANDCENTERFLYING: {
        "minerals": 400,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.ORBITALCOMMAND: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.ORBITALCOMMANDFLYING: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.PLANETARYFORTRESS: {
        "minerals": 150,
        "gas": 150,
        "supply": 0,
        "army_value": 5,
    },
    UnitTypeId.SUPPLYDEPOT: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.SUPPLYDEPOTLOWERED: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.REFINERY: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.BARRACKS: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.BARRACKSFLYING: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.ENGINEERINGBAY: {
        "minerals": 125,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.BUNKER: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 5},
    UnitTypeId.MISSILETURRET: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 1},
    UnitTypeId.AUTOTURRET: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 1},
    UnitTypeId.SENSORTOWER: {"minerals": 125, "gas": 100, "supply": 0, "army_value": 0},
    UnitTypeId.FACTORY: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitTypeId.FACTORYFLYING: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.GHOSTACADEMY: {"minerals": 150, "gas": 50, "supply": 0, "army_value": 0},
    UnitTypeId.ARMORY: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitTypeId.STARPORT: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitTypeId.STARPORTFLYING: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.FUSIONCORE: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitTypeId.TECHLAB: {"minerals": 125, "gas": 100, "supply": 0, "army_value": 0},
    UnitTypeId.BARRACKSTECHLAB: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.FACTORYTECHLAB: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.STARPORTTECHLAB: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.REACTOR: {"minerals": 50, "gas": 50, "supply": 0, "army_value": 0},
    UnitTypeId.BARRACKSREACTOR: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.FACTORYREACTOR: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.STARPORTREACTOR: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.NEXUS: {"minerals": 400, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.PYLON: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.ASSIMILATOR: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.GATEWAY: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.FORGE: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.PHOTONCANNON: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 3},
    UnitTypeId.SHIELDBATTERY: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 2},
    UnitTypeId.WARPGATE: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.CYBERNETICSCORE: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.TWILIGHTCOUNCIL: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.ROBOTICSFACILITY: {
        "minerals": 200,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.STARGATE: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitTypeId.TEMPLARARCHIVE: {
        "minerals": 150,
        "gas": 200,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.DARKSHRINE: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitTypeId.ROBOTICSBAY: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitTypeId.FLEETBEACON: {"minerals": 300, "gas": 200, "supply": 0, "army_value": 0},
    UnitTypeId.ORACLESTASISTRAP: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 1,
    },
    UnitTypeId.HATCHERY: {"minerals": 300 + 50, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.EXTRACTOR: {"minerals": 25 + 50, "gas": 0, "supply": 0, "army_value": 0},
    UnitTypeId.SPAWNINGPOOL: {
        "minerals": 200 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.EVOLUTIONCHAMBER: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.SPINECRAWLER: {
        "minerals": 100 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 3,
    },
    UnitTypeId.SPINECRAWLERUPROOTED: {
        "minerals": 100 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 3,
    },
    UnitTypeId.SPORECRAWLER: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 3,
    },
    UnitTypeId.SPORECRAWLERUPROOTED: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 3,
    },
    UnitTypeId.ROACHWARREN: {
        "minerals": 150 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.BANELINGNEST: {
        "minerals": 100 + 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.INFESTATIONPIT: {
        "minerals": 150 + 50,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.LAIR: {"minerals": 450 + 50, "gas": 100, "supply": 0, "army_value": 0},
    UnitTypeId.HIVE: {"minerals": 650 + 50, "gas": 250, "supply": 0, "army_value": 0},
    UnitTypeId.HYDRALISKDEN: {
        "minerals": 100 + 50,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.LURKERDENMP: {
        "minerals": 150 + 50,
        "gas": 150,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.SPIRE: {"minerals": 200 + 50, "gas": 200, "supply": 0, "army_value": 0},
    UnitTypeId.NYDUSNETWORK: {
        "minerals": 150 + 50,
        "gas": 200,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.NYDUSCANAL: {"minerals": 50, "gas": 50, "supply": 0, "army_value": 7},
    UnitTypeId.ULTRALISKCAVERN: {
        "minerals": 150 + 50,
        "gas": 200,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.GREATERSPIRE: {
        "minerals": 300 + 50,
        "gas": 350,
        "supply": 0,
        "army_value": 0,
    },
    UnitTypeId.CREEPTUMOR: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.1},
    UnitTypeId.CREEPTUMORBURROWED: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.1,
    },
    UnitTypeId.CREEPTUMORQUEEN: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.1,
    },
    UnitTypeId.REFINERYRICH: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0.0},
    UnitTypeId.ASSIMILATORRICH: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
    },
    UnitTypeId.EXTRACTORRICH: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
    },
}


UNIT_TYPES = [
    0,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
    117,
    118,
    119,
    120,
    125,
    126,
    127,
    128,
    129,
    130,
    131,
    132,
    133,
    134,
    135,
    136,
    137,
    138,
    139,
    140,
    141,
    142,
    143,
    144,
    145,
    146,
    147,
    149,
    150,
    151,
    268,
    289,
    311,
    321,
    322,
    324,
    330,
    335,
    336,
    341,
    342,
    343,
    344,
    350,
    364,
    365,
    371,
    372,
    373,
    376,
    377,
    472,
    473,
    474,
    475,
    483,
    484,
    485,
    486,
    487,
    488,
    489,
    490,
    493,
    494,
    495,
    496,
    498,
    499,
    500,
    501,
    502,
    503,
    504,
    517,
    518,
    559,
    560,
    561,
    562,
    563,
    564,
    588,
    589,
    590,
    591,
    608,
    609,
    610,
    612,
    628,
    629,
    630,
    638,
    639,
    640,
    641,
    642,
    643,
    648,
    649,
    651,
    661,
    662,
    663,
    664,
    665,
    666,
    687,
    688,
    689,
    690,
    691,
    692,
    693,
    694,
    732,
    733,
    734,
    796,
    797,
    801,
    824,
    830,
    877,
    880,
    881,
    884,
    885,
    886,
    887,
    892,
    893,
    894,
    1904,
    1908,
    1910,
    1911,
    1912,
    1913,
    1955,
    1956,
    1957,
    1958,
    1960,
    1961,
    1995,
]

BUFF_TYPES = [
    0,
    5,
    6,
    7,
    8,
    11,
    12,
    13,
    16,
    17,
    18,
    22,
    24,
    25,
    27,
    28,
    29,
    30,
    33,
    36,
    38,
    49,
    59,
    83,
    89,
    99,
    102,
    116,
    121,
    122,
    129,
    132,
    133,
    134,
    136,
    137,
    145,
    271,
    272,
    273,
    274,
    275,
    277,
    279,
    280,
    281,
    288,
    289,
    20,
    97,
    303,
    304,
    306,
    300,
    293,
]
